services:
  - type: web
    name: quotes-api
    env: node
    rootDir: server
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: "*"
  - type: static
    name: quotes-web
    rootDir: client
    buildCommand: "npm install && npm run build"
    staticPublishPath: "client/dist"

